name: crochetify_movil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_rating_bar: ^4.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  http: ^1.1.0
  flutter_stripe: 11.3.0
  jwt_decoder: ^2.0.1
  url_launcher: ^6.1.5
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_slider: ^5.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/datos.json
    - assets/CrochetifyLogobyDesigner.png
    - assets/categories.json
    - assets/products.json
    - assets/images/
    - assets/user.json
    - assets/cart.json
    - assets/images/carro-vacio.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/CrochetifyLogobyDesigner.png

